CREATE TABLE IF NOT EXISTS candles (
 asset TEXT NOT NULL, market TEXT NOT NULL, interval TEXT NOT NULL, time INTEGER NOT NULL,
 open REAL NOT NULL, high REAL NOT NULL, low REAL NOT NULL, close REAL NOT NULL, volume REAL NOT NULL,
 close_time INTEGER NOT NULL, fetched_at INTEGER NOT NULL,
 PRIMARY KEY(asset, market, interval, time)
);
CREATE TABLE IF NOT EXISTS onchain (
 generation TEXT NOT NULL, time INTEGER NOT NULL, data TEXT NOT NULL,
 n INTEGER NOT NULL DEFAULT 0, mean REAL NOT NULL DEFAULT 0, m2 REAL NOT NULL DEFAULT 0,
 fetched_at INTEGER NOT NULL, PRIMARY KEY(generation, time)
);
CREATE TABLE IF NOT EXISTS state (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS snapshots (key TEXT PRIMARY KEY, data TEXT NOT NULL, fetched_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion (
 key TEXT PRIMARY KEY, last_attempt INTEGER, last_success INTEGER, data_as_of INTEGER,
 error TEXT, failures INTEGER NOT NULL DEFAULT 0, next_attempt INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS raw_samples (id TEXT PRIMARY KEY, source TEXT NOT NULL, fetched_at INTEGER NOT NULL, body TEXT NOT NULL);
